apiVersion: v1
clusters:
- cluster:
    certificate-authority: ca.crt
    server: https://kube-apiserver:6443
  name: kubernetes
kind: Config
users:
- name: kubernetes-flavio
  user:
    client-certificate: admin.crt
    cliente-key: admin.key
