apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  containers:
  - name: ubuntu
    image: ubuntu-sleeper
    ports:
      - containerPort: 8080
    envFrom:
      - secretRef:
          name: app-secret
